### PR TITLE
Delegate Model Processing to parent implementation

### LINKED ISSUE #268: Does not work with polyglot-maven-extension
NB : [polyglot](https://github.com/takari/polyglot-maven) extension is [referenced on Maven web site](https://maven.apache.org/extensions/index.html)

Here following project to reproduce issue:

With following files :
<ul>
<li>.mvn/
<ul>
<li><details>
<summary>extensions.xml</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<extensions>
	<extension>
		<groupId>me.qoomon</groupId>
		<artifactId>maven-git-versioning-extension</artifactId>
		<version>9.6.6</version>
	</extension>
	<extension>
		<groupId>io.takari.polyglot</groupId>
		<artifactId>polyglot-yaml</artifactId>
		<version>0.7.0</version>
	</extension>
</extensions>
```

</details></li><li><details>
<summary>maven-git-versioning-extension.xml</summary>

```xml
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://github.com/qoomon/maven-git-versioning-extension" xsi:schemaLocation="https://github.com/qoomon/maven-git-versioning-extension https://qoomon.github.io/maven-git-versioning-extension/configuration-7.0.0.xsd">
	<refs>
		<ref type="branch">
			<pattern>.+</pattern>
			<version>${ref}-SNAPSHOT</version>
		</ref>
		<ref type="tag">
			<pattern><![CDATA[^v?(?<version>\d+\.\d+\.\d+.*)$]]></pattern>
			<version>${ref.version}</version>
		</ref>
	</refs>
	<rev>
		<version>${commit}</version>
	</rev>
</configuration>
```

</details></li>
</ul>
</li>
<li>
<details>
<summary>pom.yml</summary>

```yaml
modelEncoding: UTF-8
modelVersion: 4.0.0

groupId: com.acme
artifactId: test
version: ${revision}
packaging: pom
```

</details>
</li>
</ul>

When execute following command:
```bash
mvn help:evaluate -Dexpression=project.version
```

 `maven-git-versioning-extension` dose not seems to work:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------------< com.acme:test >----------------------------
[INFO] Building test ${revision}
[INFO]   from .polyglot.pom.yml
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- help:3.4.0:evaluate (default-cli) @ test ---
[INFO] No artifact parameter specified, using 'com.acme:test:pom:${revision}' as project.
[INFO] 
null object or invalid expression
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.179 s
[INFO] Finished at: 2023-12-30T00:27:49+01:00
[INFO] ------------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by jycr**
By default, _Eclipse Sisu_ IoC implementation knows all candidates of `org.apache.maven.model.building.ModelProcessor` implementation.
So, there is always `org.apache.maven.model.building.DefaultModelProcessor` in this list (as well as the current `me.qoomon.maven.gitversioning.GitVersioningModelProcessor`).

When a project uses another custom `ModelProcessor` like the [polyglot](https://github.com/takari/polyglot-maven) extension (see [Maven Website](https://maven.apache.org/extensions/index.html)), this list also contains this alternative implementation.

This change allows delegating core methods (`File locatePom( File projectDirectory )` and `Model read(...)`) to the "parent implementation" (defaults to `org.apache.maven.model.building. ModelProcessor` or a custom implementation if applicable).

This PR fixes #268

### CODE REVIEW

**Comment by qoomon** [comment]
@jycr thx for your PR I came up with basically the same idea :-D, however I went for setter injection of all Processors.
I tend to like setter injection a little more, because it is easier to read. WDYT?

```java
    @Inject
    private void setDelegatedModelProcessor(List<ModelProcessor> modelProcessors) {
        this.delegatedModelProcessor = modelProcessors.stream()
                .filter(it -> it != this)
                // There is normally always at least one implementation available: org.apache.maven.model.building.DefaultModelProcessor
                .findFirst().orElseThrow(() -> new NoSuchElementException("Unable to find default ModelProcessor"));
    }
```

**Comment by jycr** [comment]
> @jycr thx for your PR I came up with basically the same idea :-D, however I went for setter injection of all Processors. I tend to like setter injection a little more, because it is easier to read. WDYT?
> 
> ```java
>     @Inject
>     private void setDelegatedModelProcessor(List<ModelProcessor> modelProcessors) {
>         this.delegatedModelProcessor = modelProcessors.stream()
>                 .filter(it -> it != this)
>                 // There is normally always at least one implementation available: org.apache.maven.model.building.DefaultModelProcessor
>                 .findFirst().orElseThrow(() -> new NoSuchElementException("Unable to find default ModelProcessor"));
>     }
> ```

Why not :)
For my part, I prefer dependency injection by constructor.
I'll push a new commit to follow your idea.

**Comment by qoomon** [comment]
There is one more issue, we need to tackle or at least throw an appropriate error.
At following line I need to write the artificial `pom.xml` to do that I first read the original one, however in case of `polyglot-yaml` extension the source is a yaml file. See  `projectModel.getPomFile()` returns `pom.yaml` 
https://github.com/qoomon/maven-git-versioning-extension/blob/59c80d2dfabbc6b44f0291ad6c2c17f3b12a7040/src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java#L1166

I think, if the pom file is not an xml file I should skip the pom.xml file processing and just generate a pom.xml from the `projectModel`

How is it intended to work for the polyglot extensions e.g. if you release something to maven central. Will polyglot extensions generate an pom.xml as well?

**Comment by jycr** [comment]
> There is one more issue, we need to tackle or at least throw an appropriate error. At following line I need to write the artificial `pom.xml` to do that I first read the original one, however in case of `polyglot-yaml` extension the source is a yaml file. See `projectModel.getPomFile()` returns `pom.yaml`
> 
> https://github.com/qoomon/maven-git-versioning-extension/blob/59c80d2dfabbc6b44f0291ad6c2c17f3b12a7040/src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java#L1166
> 
> I think, if the pom file is not an xml file I should skip the pom.xml file processing and just generate a pom.xml from the `projectModel`
> 
> How is it intended to work for the polyglot extensions e.g. if you release something to maven central. Will polyglot extensions generate an pom.xml as well?

Indeed, I call `File locatePom(File projectDirectory)` instead of calling `projectModel.getPomFile()` to prevent this issue

**Comment by qoomon** [comment]
...and obviously the update pom feature is not supported as well

**Comment by jycr** [comment]
> ...and obviously the update pom feature is not supported as well

I think that this is indeed a limitation that remains for the use of several ModelProcessors (in particular for the use of Maven Polyglot).
However, I don't think this option is used by the majority of users of this extension?

**Comment by qoomon** [comment]
I came up with following solution that works on my machine
```java
 private File writePomFile(Model projectModel) throws IOException {
        File gitVersionedPomFile = new File(projectModel.getProjectDirectory(), GIT_VERSIONING_POM_NAME);
        logger.debug("generate " + gitVersionedPomFile);

        if(projectModel.getPomFile().getName().endsWith(".xml")) {
            // read original pom file
            Document gitVersionedPomDocument = readXml(projectModel.getPomFile());
            Element projectElement = gitVersionedPomDocument.getChild("project");

            // update project
            updateParentVersion(projectElement, projectModel.getParent());
            updateVersion(projectElement, projectModel);
            updatePropertyValues(projectElement, projectModel);
            updateDependencyVersions(projectElement, projectModel);
            updatePluginVersions(projectElement, projectModel.getBuild(), projectModel.getReporting());

            updateProfiles(projectElement, projectModel.getProfiles());

            writeXml(gitVersionedPomFile, gitVersionedPomDocument);
        } else {
            writeModel(gitVersionedPomFile, projectModel);
        }

        return gitVersionedPomFile;
    }
```

**Comment by qoomon** [comment]
> Indeed, I call File locatePom(File projectDirectory) instead of calling projectModel.getPomFile() to prevent this issue
I think this also only works by accident, because the method documentation does not say anything about what kind of pom file it should return.

**Comment by jycr** [comment]
> I came up with following solution that works on my machine
> 
> ```java
>  private File writePomFile(Model projectModel) throws IOException {
>         File gitVersionedPomFile = new File(projectModel.getProjectDirectory(), GIT_VERSIONING_POM_NAME);
>         logger.debug("generate " + gitVersionedPomFile);
> 
>         if(projectModel.getPomFile().getName().endsWith(".xml")) {
>             // read original pom file
>             Document gitVersionedPomDocument = readXml(projectModel.getPomFile());
>             Element projectElement = gitVersionedPomDocument.getChild("project");
> 
>             // update project
>             updateParentVersion(projectElement, projectModel.getParent());
>             updateVersion(projectElement, projectModel);
>             updatePropertyValues(projectElement, projectModel);
>             updateDependencyVersions(projectElement, projectModel);
>             updatePluginVersions(projectElement, projectModel.getBuild(), projectModel.getReporting());
> 
>             updateProfiles(projectElement, projectModel.getProfiles());
> 
>             writeXml(gitVersionedPomFile, gitVersionedPomDocument);
>         } else {
>             writeModel(gitVersionedPomFile, projectModel);
>         }
> 
>         return gitVersionedPomFile;
>     }
> ```

I don't think that this modification is needed.

You can only write POM in XML langage.

So, I will modify:

```java
        if (updatePom) {
            logger.debug("updating original POM file");
            Files.copy(
                    gitVersionedPomFile.toPath(),
                    projectModel.getPomFile().toPath(),
                    StandardCopyOption.REPLACE_EXISTING);
        }
```

by

```java
        if (updatePom) {
            logger.debug("updating original POM file");
            Files.copy(
                    gitVersionedPomFile.toPath(),
                    locatePom(projectModel.getProjectDirectory()).toPath(),
                    StandardCopyOption.REPLACE_EXISTING);
        }
```

**Comment by qoomon** [comment]
You need to handle the yaml pom on two places (in writePomFile(), and in case of updatePom feature is used)

```java
        File gitVersionedPomFile = writePomFile(projectModel);
        if (updatePom) {
            if(projectModel.getPomFile().getName().endsWith(".xml")) {
                logger.debug("updating original POM file");
                Files.copy(
                        gitVersionedPomFile.toPath(),
                        projectModel.getPomFile().toPath(),
                        StandardCopyOption.REPLACE_EXISTING);
            } else {
               logger.warn("updating original POM file only works for pom.xml files");
            }
        }
```

**Comment by jycr** [comment]
In `writePomFile` I get XML translated File (if Polyglot extension used) or regular `pom.xml` (if no other ModelProcessor used) :

```java
Document gitVersionedPomDocument = readXml(this.locatePom(projectModel.getProjectDirectory()));
```

if `updatePom` feature is used, it updates the XML translated File (if Polyglot extension used) or regular `pom.xml` (if no other ModelProcessor used):

```java
Files.copy(
    gitVersionedPomFile.toPath(),
    locatePom(projectModel.getProjectDirectory()).toPath(),
    StandardCopyOption.REPLACE_EXISTING);
```

**Comment by qoomon** [comment]
Well, lets try

File: src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java [hunk 1]
```diff
@@ -125,7 +143,7 @@ private void init(Model projectModel) throws IOException {
             logger.info(extensionLogHeader(BuildProperties.projectGAV()));
         }
 
-        File pomFile = projectModel.getPomFile();
+        File pomFile = locatePom(projectModel.getProjectDirectory());
```
Comment (qoomon) [inline src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java:146]: I think we need to a comment why locatePom() is used instead of the more obvious projectModel.getPomFile()

Comment (qoomon) [reply src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java:146]: Should we store pomFile as a class variable to use it later again, instead of calling  locatePom again

File: src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java [hunk 2]
```diff
@@ -303,7 +321,7 @@ public Model processModel(Model projectModel, Map<String, ?> options) throws IOE
             logger.debug("updating original POM file");
             Files.copy(
                     gitVersionedPomFile.toPath(),
-                    projectModel.getPomFile().toPath(),
+                    locatePom(projectModel.getProjectDirectory()).toPath(),
```
Comment (qoomon) [inline src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java:324]: Need a comment as well

File: src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java [hunk 3]
```diff
@@ -1179,7 +1197,7 @@ private File writePomFile(Model projectModel) throws IOException {
         logger.debug("generate {}", gitVersionedPomFile);
 
         // read original pom file
-        Document gitVersionedPomDocument = readXml(projectModel.getPomFile());
+        Document gitVersionedPomDocument = readXml(this.locatePom(projectModel.getProjectDirectory()));
```
Comment (qoomon) [inline src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java:1200]: Need a comment as well

**Review by qoomon — APPROVED** [review]

File: src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java [hunk 4]
```diff
@@ -1418,4 +1441,9 @@ private static String increase(String number, long increment) {
         String sanitized = number.isEmpty() ? "0" : number;
         return String.format("%0" + sanitized.length() + "d", Long.parseLong(number.isEmpty() ? "0" : number) + increment);
     }
+
+    @Override
```
Comment (qoomon) [inline src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java:1445]: Please move this method up to line 119 to the other overridden methods

**Review by qoomon — APPROVED** [review]
